# -*- coding: utf-8 -*-

MOD_NAMESPACE = 'KillBroadcast'
MOD_BINDING_NAME = 'KillBroadcastScript'
MOD_RESOURCE_ID = '4689250047043221145'
SERVER_SYSTEM_NAME = 'KillBroadcastServerSystem'
SERVER_SYSTEM_PATH = 'KillBroadcastScript.Server.KillBroadcastServerSystem'
CLIENT_SYSTEM_NAME = 'KillBroadcastClientSystem'
CLIENT_SYSTEM_PATH = 'KillBroadcastScript.Client.Client.KillBroadcastClientSystem'

CREATE_KILL_EVENT = 'CreateKill'
HIT_MARKER_EVENT = 'HitMarker'
HEADSHOT_SOUND_EVENT = 'HeadshotSound'
PLAYER_DEATH_CLEANUP_EVENT = 'PlayerDeathCleanup'
SERVER_STATUS_EVENT = 'CompatibilityStatus'
AIM_SNAPSHOT_EVENT = 'AimSnapshot'

TSGUNS_NAMESPACE = 'TsGuns'
TSGUNS_SERVER_SYSTEM = 'TsGunsServerSystem'
TSGUNS_CLIENT_SYSTEM = 'TsGunsClientSystem'

COMPAT_NAMESPACE = 'KillBroadcastCompat'
HIDE_KILL_SETTINGS_SYSTEM = 'HideKillEffectSettings'

KILL_SOURCE_GENERIC = 'generic'
KILL_SOURCE_EXTERNAL = 'external'
DEATH_LOCK_SECONDS = 10.0
PENDING_LETHAL_CONFIRM_TICKS = 1
PENDING_LETHAL_EXPIRE_TICKS = 3
HIT_MARKER_DEDUP_SECONDS = 0.04
HEADSHOT_SOUND_RADIUS = 32.0
HEADSHOT_SOUND_RADIUS_SQ = HEADSHOT_SOUND_RADIUS * HEADSHOT_SOUND_RADIUS
DAMAGE_CONTEXT_SECONDS = 8.0
CORPSE_KILL_CONTEXT_SECONDS = 1.0
PROJECTILE_CONTEXT_SECONDS = 30.0
AIM_SNAPSHOT_INTERVAL_SECONDS = 0.05
AIM_SNAPSHOT_HEARTBEAT_SECONDS = 0.20
AIM_SNAPSHOT_POSITION_EPSILON_SQ = 0.0025
AIM_SNAPSHOT_DIRECTION_DOT_THRESHOLD = 0.9999
AIM_SNAPSHOT_SERVER_MIN_INTERVAL_SECONDS = 0.025
AIM_SNAPSHOT_MAX_AGE_SECONDS = 0.25
AIM_SNAPSHOT_MAX_CAMERA_DISTANCE = 8.0
HEADSHOT_RAY_MAX_DISTANCE = 128.0
HEADSHOT_EYE_HEIGHT = 1.62
HEADSHOT_SNEAK_EYE_OFFSET = 0.20
HEADSHOT_STANDING_HEIGHT = (1.45, 1.92)
HEADSHOT_SNEAKING_HEIGHT = (1.18, 1.65)
HEADSHOT_PLAYER_BODY_HALF_WIDTH = 0.30
HEADSHOT_PLAYER_BODY_HEIGHT = 1.90
HEADSHOT_PLAYER_SNEAKING_BODY_HEIGHT = 1.65
HEADSHOT_ENTITY_TOP_RATIO = 0.72
